swagger: "2.0"
info:
    title: Books Service
    description: CRUD Application for books
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /books:
        get:
            tags:
                - books
            summary: all books
            operationId: books#all
            responses:
                "200":
                    description: OK response.
                    schema:
                        type: array
                        items:
                            $ref: '#/definitions/BookResponse'
            schemes:
                - http
        post:
            tags:
                - books
            summary: create books
            operationId: books#create
            parameters:
                - name: CreateRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BooksCreateRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksCreateResponseBody'
            schemes:
                - http
    /books/{id}:
        get:
            tags:
                - books
            summary: getBook books
            operationId: books#getBook
            parameters:
                - name: id
                  in: path
                  description: Book ID
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksGetBookResponseBody'
            schemes:
                - http
        put:
            tags:
                - books
            summary: updateBook books
            operationId: books#updateBook
            parameters:
                - name: id
                  in: path
                  description: Book ID
                  required: true
                  type: integer
                - name: UpdateBookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BooksUpdateBookRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BooksUpdateBookResponseBody'
            schemes:
                - http
        delete:
            tags:
                - books
            summary: deleteBook books
            operationId: books#deleteBook
            parameters:
                - name: id
                  in: path
                  description: Book ID
                  required: true
                  type: integer
            responses:
                "204":
                    description: No Content response.
            schemes:
                - http
    /openapi3.json:
        get:
            tags:
                - books
            summary: Download ./gen/http/openapi3.json
            operationId: books#/openapi3.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    BookRequestBody:
        title: BookRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Distinctio sed occaecati sequi veniam.
            bookCover:
                type: string
                description: Cover of the book
                example: Omnis voluptate velit ratione sint voluptatibus quos.
            id:
                type: integer
                description: Unique ID of the book
                example: 5316936788496684629
                format: int64
            publishedAt:
                type: string
                description: Date the book has been published
                example: Sed nihil fugit minima cupiditate.
            title:
                type: string
                description: Title of the book
                example: Odit repellendus rerum.
        example:
            author: Aut qui quis distinctio labore.
            bookCover: Incidunt dignissimos sed omnis.
            id: 8207999670637457491
            publishedAt: Id rem libero a sunt.
            title: Cupiditate consectetur.
    BookResponse:
        title: BookResponse
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Optio sed vitae a amet distinctio.
            bookCover:
                type: string
                description: Cover of the book
                example: Ea inventore porro assumenda recusandae corrupti.
            id:
                type: integer
                description: Unique ID of the book
                example: 9094929035047170638
                format: int64
            publishedAt:
                type: string
                description: Date the book has been published
                example: Doloribus similique possimus quia.
            title:
                type: string
                description: Title of the book
                example: Autem debitis.
        example:
            author: Voluptatem voluptatem ut ex et quasi.
            bookCover: Qui et deleniti fugit est aut.
            id: 933868219178393708
            publishedAt: Et enim odio voluptatum.
            title: Eos facere placeat veniam voluptas accusamus ut.
    BooksCreateRequestBody:
        title: BooksCreateRequestBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Eum dolorum labore quas quidem sit.
            bookCover:
                type: string
                description: Cover of the book
                example: Rerum illum vel qui totam incidunt aut.
            id:
                type: integer
                description: Unique ID of the book
                example: 3537087644036652157
                format: int64
            publishedAt:
                type: string
                description: Date the book has been published
                example: Mollitia error ratione delectus quas temporibus possimus.
            title:
                type: string
                description: Title of the book
                example: Voluptate quo veritatis doloribus nesciunt.
        example:
            author: Et qui.
            bookCover: Voluptatem sit quasi.
            id: 8251783029889772279
            publishedAt: Nemo praesentium dolorem et vitae sunt a.
            title: Amet provident velit voluptate.
    BooksCreateResponseBody:
        title: BooksCreateResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Amet iste saepe.
            bookCover:
                type: string
                description: Cover of the book
                example: Est temporibus voluptatibus occaecati sint.
            id:
                type: integer
                description: Unique ID of the book
                example: 6856166057270081167
                format: int64
            publishedAt:
                type: string
                description: Date the book has been published
                example: Assumenda sed placeat perferendis quia.
            title:
                type: string
                description: Title of the book
                example: Odit tenetur.
        example:
            author: Velit et unde eveniet.
            bookCover: Aliquam laboriosam in molestiae repudiandae.
            id: 2152028917879035118
            publishedAt: Et amet dolores qui quam.
            title: Consequuntur ut alias eos magnam qui quibusdam.
    BooksGetBookResponseBody:
        title: BooksGetBookResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Corrupti saepe laudantium qui eligendi.
            bookCover:
                type: string
                description: Cover of the book
                example: Fuga est sed blanditiis et.
            id:
                type: integer
                description: Unique ID of the book
                example: 7244139769867850733
                format: int64
            publishedAt:
                type: string
                description: Date the book has been published
                example: Neque voluptas sequi soluta consequatur.
            title:
                type: string
                description: Title of the book
                example: Aut doloribus expedita autem quis iusto dolorem.
        example:
            author: Dolore exercitationem ex odit.
            bookCover: Est ut est sit et perferendis.
            id: 1588809184003176921
            publishedAt: Eos aperiam illum consequatur voluptatem illo tempora.
            title: Ut quis hic et dicta et eum.
    BooksUpdateBookRequestBody:
        title: BooksUpdateBookRequestBody
        type: object
        properties:
            book:
                $ref: '#/definitions/BookRequestBody'
        example:
            book:
                author: Eum maiores maxime.
                bookCover: Non dolores quasi saepe sunt est dolor.
                id: 4940795916846100831
                publishedAt: Expedita commodi facere magni et.
                title: Eos consequuntur tempore.
    BooksUpdateBookResponseBody:
        title: BooksUpdateBookResponseBody
        type: object
        properties:
            author:
                type: string
                description: Author of the book
                example: Sed aut.
            bookCover:
                type: string
                description: Cover of the book
                example: Iste accusantium quo aliquam sit.
            id:
                type: integer
                description: Unique ID of the book
                example: 8832309096929784805
                format: int64
            publishedAt:
                type: string
                description: Date the book has been published
                example: Numquam consequatur fuga voluptatibus alias et fugit.
            title:
                type: string
                description: Title of the book
                example: Quia consequatur.
        example:
            author: Veritatis delectus voluptatem tenetur eveniet earum voluptatem.
            bookCover: Error officiis et.
            id: 3898703780982607212
            publishedAt: Dolorum quas.
            title: Quas et.
